#include <ESPressio_Adapters.hpp>
#include "AdapterHostRuntime.hpp"
#include <atomic>
#include <cassert>
#include <thread>
using namespace ESPressio::Adapters;
using Arena=StaticByteArena<ByteClass<64,8>,ByteClass<256,4>>;using Domain=StaticCapacityDomain<1024,8,Arena>;using Inbound=CapacityPlane<AdapterDirection::Inbound,Domain,Domain,Domain,Domain,Domain,Domain,Domain,Domain>;using Outbound=CapacityPlane<AdapterDirection::Outbound,Domain,Domain,Domain,Domain,Domain,Domain,Domain>;using Runtime=AdapterRuntime<Inbound,Outbound,2,4,1,1,8>;
struct Blocker final {std::atomic<unsigned> Calls{0},Completions{0};std::atomic<bool> Entered{false},AllowFinish{false};static ESPressio::Primitive::PrimitiveAdmissionDisposition Admit(void* c,ESPressio::Primitive::PrimitiveProtocolVersion,AdapterByteView,const AdapterSemanticProvenance&) noexcept {auto& b=*static_cast<Blocker*>(c);++b.Calls;b.Entered=true;while(!b.AllowFinish.load(std::memory_order_acquire))std::this_thread::yield();return ESPressio::Primitive::PrimitiveAdmissionDisposition::Accepted;}static void Complete(void* c,const AdapterInboundCompletion&) noexcept{++static_cast<Blocker*>(c)->Completions;}};
struct OutboundBlocker final {std::atomic<unsigned> SubmitCalls{0},CancelCalls{0},QuiesceCalls{0};std::atomic<bool> SubmitEntered{false},AllowSubmitReturn{false};static AdapterEncodeResult Encode(void*,ESPressio::Primitive::PrimitiveProtocolVersion,std::uint64_t,const void* source,AdapterMutableByteView out) noexcept {if(!source||out.Capacity<1)return{AdapterResourceStatus::InvalidLength,0};out.Data[0]=*static_cast<const std::uint8_t*>(source);return{AdapterResourceStatus::Success,1};}static bool Validate(void*) noexcept{return true;}static LowerTransportSubmitResult Submit(void* c,AdapterRecordIdentity,AdapterServiceClass,AdapterByteView,AdapterRouteToken) noexcept {auto& b=*static_cast<OutboundBlocker*>(c);++b.SubmitCalls;b.SubmitEntered=true;while(!b.AllowSubmitReturn.load(std::memory_order_acquire))std::this_thread::yield();return{LowerTransportDisposition::Accepted,77,true};}static void Cancel(void* c,AdapterRecordIdentity) noexcept{++static_cast<OutboundBlocker*>(c)->CancelCalls;}static void Quiesce(void* c) noexcept{++static_cast<OutboundBlocker*>(c)->QuiesceCalls;}};
static ESPressio::Primitive::PrimitivePolicyDescriptor OneShot(){ESPressio::Primitive::PrimitivePolicyDescriptor p{};p.MaximumAttempts=1;p.MaximumResidenceNanoseconds=0;return p;}
static ESPressio::Primitive::PrimitivePolicyDescriptor EvidencePolicy(){ESPressio::Primitive::PrimitivePolicyDescriptor p{};p.Evidence=1;p.MaximumAttempts=2;p.MaximumResidenceNanoseconds=1'000'000'000ULL;p.MaximumAdapterAdmissionWaitNanoseconds=100'000'000ULL;p.MinimumRetrySpacingNanoseconds=0;p.MaximumRetrySpacingNanoseconds=100'000'000ULL;return p;}
int main(){AdapterHostRuntime host;
 {Blocker blocker;Runtime runtime;AdapterBindingDescriptor binding{};binding.Family=1;binding.Protocols={1,1};binding.MaximumInboundBytes=16;binding.ServiceClassMask=std::uint8_t{1}<<static_cast<unsigned>(AdapterServiceClass::Critical);binding.Owner=&blocker;binding.AdmitInbound=&Blocker::Admit;assert(runtime.BindFamily(binding)==AdapterRuntimeStatus::Success);assert(runtime.Initialize()==AdapterRuntimeStatus::Success);assert(runtime.Start()==AdapterRuntimeStatus::Success);std::uint8_t first=1,second=2;AdapterInboundCompletionTarget completion{&blocker,&Blocker::Complete};assert(runtime.AdmitTrustedInbound(1,AdapterServiceClass::Critical,1,{&first,1},{},{},OneShot(),1,completion)==AdapterSubmissionDisposition::Accepted);while(!blocker.Entered.load(std::memory_order_acquire))std::this_thread::yield();assert(runtime.AdmitTrustedInbound(1,AdapterServiceClass::Critical,1,{&second,1},{},{},OneShot(),2,completion)==AdapterSubmissionDisposition::Accepted);std::atomic<bool> shutdownDone{false};std::thread shutdown([&]{assert(runtime.Shutdown()==AdapterRuntimeStatus::Success);shutdownDone=true;});for(unsigned i=0;i<1000;++i)std::this_thread::yield();assert(!shutdownDone.load(std::memory_order_acquire));blocker.AllowFinish=true;shutdown.join();assert(shutdownDone&&blocker.Calls==1&&blocker.Completions==1);assert(!runtime.IsRunning()&&!runtime.IsInitialized());}
 {OutboundBlocker blocker;Runtime runtime;AdapterBindingDescriptor binding{};binding.Family=2;binding.Protocols={1,1};binding.MaximumOutboundBytes=16;binding.ServiceClassMask=std::uint8_t{1}<<static_cast<unsigned>(AdapterServiceClass::Responsive);binding.Owner=&blocker;binding.EncodeOutbound=&OutboundBlocker::Encode;binding.RequiresDestinationAdmissionEvidence=true;LowerTransportBinding transport{};transport.Owner=&blocker;transport.Validate=&OutboundBlocker::Validate;transport.Submit=&OutboundBlocker::Submit;transport.Cancel=&OutboundBlocker::Cancel;transport.Quiesce=&OutboundBlocker::Quiesce;transport.ServiceClassMask=0x3f;transport.ProvidesDestinationPrimitiveAdmission=true;assert(runtime.BindFamily(binding)==AdapterRuntimeStatus::Success);assert(runtime.BindTransport(transport)==AdapterRuntimeStatus::Success);assert(runtime.Initialize()==AdapterRuntimeStatus::Success);assert(runtime.Start()==AdapterRuntimeStatus::Success);std::uint8_t source=9;assert(runtime.SubmitOutbound(2,AdapterServiceClass::Responsive,1,&source,{7},EvidencePolicy(),3)==AdapterSubmissionDisposition::Accepted);while(!blocker.SubmitEntered.load(std::memory_order_acquire))std::this_thread::yield();std::atomic<bool> shutdownDone{false};std::thread shutdown([&]{assert(runtime.Shutdown()==AdapterRuntimeStatus::Success);shutdownDone=true;});while(blocker.QuiesceCalls.load(std::memory_order_acquire)==0)std::this_thread::yield();assert(!shutdownDone.load(std::memory_order_acquire));blocker.AllowSubmitReturn=true;shutdown.join();assert(blocker.SubmitCalls==1&&blocker.QuiesceCalls==1&&blocker.CancelCalls==1);assert(!runtime.IsRunning()&&!runtime.IsInitialized());}
}
