#include <ESPressio_Adapters.hpp>
#include "AdapterHostRuntime.hpp"
#include <atomic>
#include <cassert>
#include <cstdlib>
#include <new>
static std::atomic<bool> DenyHeap{false};
void* operator new(std::size_t n){if(DenyHeap.load(std::memory_order_relaxed))std::abort();if(void* p=std::malloc(n))return p;std::abort();}
void operator delete(void* p) noexcept{std::free(p);}void operator delete(void* p,std::size_t) noexcept{std::free(p);}void* operator new[](std::size_t n){return ::operator new(n);}void operator delete[](void* p) noexcept{::operator delete(p);}void operator delete[](void* p,std::size_t) noexcept{::operator delete(p);}
using namespace ESPressio::Adapters;using Arena=StaticByteArena<ByteClass<64,12>,ByteClass<256,6>>;using Domain=StaticCapacityDomain<1024,6,Arena>;using Inbound=CapacityPlane<AdapterDirection::Inbound,Domain,Domain,Domain,Domain,Domain,Domain,Domain,Domain>;using Outbound=CapacityPlane<AdapterDirection::Outbound,Domain,Domain,Domain,Domain,Domain,Domain,Domain>;using Runtime=AdapterRuntime<Inbound,Outbound,2,4,1,1,8>;
struct H{std::atomic<unsigned> Admit{0},Submit{0},Feedback{0};static ESPressio::Primitive::PrimitiveAdmissionDisposition A(void*c,ESPressio::Primitive::PrimitiveProtocolVersion,AdapterByteView,const AdapterSemanticProvenance&)noexcept{++static_cast<H*>(c)->Admit;return ESPressio::Primitive::PrimitiveAdmissionDisposition::Accepted;}static AdapterEncodeResult E(void*,ESPressio::Primitive::PrimitiveProtocolVersion,std::uint64_t,const void* s,AdapterMutableByteView o)noexcept{o.Data[0]=*static_cast<const std::uint8_t*>(s);return{AdapterResourceStatus::Success,1};}static void F(void*c,const AdapterFamilyFeedback&)noexcept{++static_cast<H*>(c)->Feedback;}static bool V(void*)noexcept{return true;}static LowerTransportSubmitResult S(void*c,AdapterRecordIdentity,ESPressio::Primitive::PrimitiveFamilyId,ESPressio::Primitive::PrimitiveProtocolVersion,const ESPressio::Primitive::PrimitivePolicyDescriptor&,AdapterServiceClass,AdapterByteView,AdapterRouteToken)noexcept{++static_cast<H*>(c)->Submit;return{LowerTransportDisposition::Accepted,1,false};}};
int main(){AdapterHostRuntime host;H h;Runtime r;AdapterBindingDescriptor b{};b.Family=1;b.Protocols={1,1};b.MaximumInboundBytes=32;b.MaximumOutboundBytes=32;b.ServiceClassMask=std::uint8_t{1}<<static_cast<unsigned>(AdapterServiceClass::Responsive);b.Owner=&h;b.AdmitInbound=&H::A;b.EncodeOutbound=&H::E;b.Feedback=&H::F;assert(r.BindFamily(b)==AdapterRuntimeStatus::Success);LowerTransportBinding t{};t.Owner=&h;t.Submit=&H::S;t.Validate=&H::V;t.ServiceClassMask=0x3f;assert(r.BindTransport(t)==AdapterRuntimeStatus::Success);assert(r.Initialize()==AdapterRuntimeStatus::Success);assert(r.Start()==AdapterRuntimeStatus::Success);ESPressio::Primitive::PrimitivePolicyDescriptor p{};p.MaximumAttempts=1;p.MaximumResidenceNanoseconds=0;std::uint8_t value=7;DenyHeap=true;assert(r.AdmitTrustedInbound(1,AdapterServiceClass::Responsive,1,{&value,1},{},{},p,1)==AdapterSubmissionDisposition::Accepted);assert(r.SubmitOutbound(1,AdapterServiceClass::Responsive,1,&value,{1},p,2)==AdapterSubmissionDisposition::Accepted);WaitUntil(h.Admit,1);WaitUntil(h.Submit,1);WaitUntil(h.Feedback,1);DenyHeap=false;assert(r.Shutdown()==AdapterRuntimeStatus::Success);}
